name: New

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project-matrix: ${{ steps.subdirectories.outputs.BALLERINA_PROJECT_PATHS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Testing
        run: |
          ls

      - name: Set up Ballerina
        run: |
          # Pull the Ballerina Docker image
          docker pull ballerina/ballerina:2201.6.0

          # Run the Docker container
          docker run -d --name ballerina-container -v $(pwd):/app ballerina/ballerina:2201.6.0 tail -f /dev/null

          # Copy everything to the container
          docker cp . ballerina-container:/app

          # Execute 'ls' command inside the container
          docker exec ballerina-container ls

          # Clean up the container
          docker rm -f ballerina-container