name: New

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project-matrix: ${{ steps.subdirectories.outputs.BALLERINA_PROJECT_PATHS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Testing
        run: |
          ls

      - name: Build and run container
        env:
          BALLERINA_VERSION: 2201.6.0
        run: |
          docker build --build-arg BALLERINA_VERSION=$BALLERINA_VERSION -t my-ballerina-app .
          docker run my-ballerina-app
        working-directory: ${{ steps.checkout.outputs.checkout-path }}

      - name: Execute ls in the container
        run: |
          docker run my-ballerina-app ls
