name: New

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project-matrix: ${{ steps.subdirectories.outputs.BALLERINA_PROJECT_PATHS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Testing
        run: |
          ls

      - name: Set up Ballerina
        run: |
          # Pull the Ballerina Docker image
          docker pull ballerina/ballerina:2201.6.0

      - name: Create entrypoint.sh
        run: |
          # Create the entrypoint.sh script to list files in the container
          echo '#!/bin/sh' > entrypoint.sh
          echo 'ls -la' >> entrypoint.sh
          chmod +x entrypoint.sh

      - name: Set DOCKER_API_VERSION environment variable
        run: |
          # Set the DOCKER_API_VERSION environment variable
          echo 'DOCKER_API_VERSION="v1.38"' >> $GITHUB_ENV

      - name: Run Docker container
        run: |
          # Run the Docker container with the specified entrypoint
          docker run --env-file $GITHUB_ENV --user root -v $PWD:/ -w / --entrypoint "/entrypoint.sh" ballerina/ballerina:2201.6.0
