name: Weekly Build

on:
  schedule:
    - cron:  '30 18 * * 0'    # 00:00 on Sundays in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-20.04-16core
    outputs:
      project-matrix: ${{ steps.subdirectories.outputs.BALLERINA_PROJECT_PATHS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Ballerina Project Paths
        id: subdirectories
        run: |
          SUBDIRS=$(ls -d */)
          SUBDIRS="${SUBDIRS//\/}"
          SUBDIRS_JSON=$(echo "$SUBDIRS" | jq -R -s -c 'split("\n")[:-1]')
          echo "$SUBDIRS_JSON"
          echo "BALLERINA_PROJECT_PATHS=${SUBDIRS_JSON}" >> $GITHUB_OUTPUT

  run:
    needs: [ setup ]
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx8G
    if: ${{ needs.setup.outputs.project-matrix != '[]' }}
    strategy:
      matrix:
        path: ${{ fromJson(needs.setup.outputs.project-matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ballerina Run
        uses: ballerina-platform/ballerina-action@2201.5.0
        with:
          args: run
        env:
          WORKING_DIR: ./${{ matrix.path }}
          JAVA_HOME: /usr/lib/jvm/default-jvm
